from __future__ import annotations

CITY_OPTIONS: tuple[dict[str, str], ...] = (
    {"name": '杭州', "id": '42', "pinyin": 'hangzhou', "city_no": 'hangzhou'},
    {"name": '温州', "id": '10', "pinyin": 'WENZHOU', "city_no": 'WENZHOU'},
    {"name": '长沙', "id": '62', "pinyin": 'CHANGSHA', "city_no": 'CHANGSHA'},
    {"name": '醴陵', "id": '113', "pinyin": 'liling', "city_no": 'liling'},
    {"name": '新乡', "id": '59', "pinyin": 'XINXIANG', "city_no": 'XINXIANG'},
    {"name": '诸城', "id": '22', "pinyin": 'ZHUCHENG', "city_no": 'ZHUCHENG'},
    {"name": '兴化', "id": '51', "pinyin": 'XINGHUA', "city_no": 'XINGHUA'},
    {"name": '泰安', "id": '202', "pinyin": 'taian', "city_no": 'taian'},
    {"name": '宁晋', "id": '291', "pinyin": 'ningjin', "city_no": 'NJ'},
    {"name": '哈尔滨', "id": '251', "pinyin": 'haerbin', "city_no": 'haerbin'},
    {"name": '滦州', "id": '183', "pinyin": 'luanzhou', "city_no": 'luanzhou'},
    {"name": '马鞍山', "id": '267', "pinyin": 'MAANSHAN', "city_no": 'MAANSHAN'},
    {"name": '高邮', "id": '52', "pinyin": 'gaoyou', "city_no": 'gaoyou'},
    {"name": '泾县', "id": '286', "pinyin": 'JINGXIAN', "city_no": 'JINGXIAN'},
    {"name": '宁德', "id": '94', "pinyin": 'NINGDE', "city_no": 'NINGDE'},
    {"name": '鹿泉', "id": '135', "pinyin": 'luquan', "city_no": 'luquan'},
    {"name": '六安', "id": '4', "pinyin": 'LIUAN', "city_no": 'LIUAN'},
    {"name": '泉港', "id": '84', "pinyin": 'quangang', "city_no": 'quangang'},
    {"name": '嘉善', "id": '346', "pinyin": 'jiashan', "city_no": 'jiashan'},
    {"name": '石狮', "id": '69', "pinyin": 'SHISHI', "city_no": 'SHISHI'},
    {"name": '安溪', "id": '78', "pinyin": 'anxi', "city_no": 'anxi'},
    {"name": '城阳', "id": '75', "pinyin": 'CHENGYANG', "city_no": 'CHENGYANG'},
    {"name": '烟台', "id": '38', "pinyin": 'YANTAI', "city_no": 'YANTAI'},
    {"name": '盱眙', "id": '332', "pinyin": 'XUYI', "city_no": 'XUYI'},
    {"name": '增城', "id": '184', "pinyin": 'zengcheng', "city_no": 'zengcheng'},
    {"name": '滨州', "id": '265', "pinyin": 'binzhou', "city_no": 'binzhou'},
    {"name": '湖州', "id": '90', "pinyin": 'HUZHOU', "city_no": 'HUZHOU'},
    {"name": '大丰', "id": '339', "pinyin": 'dafeng', "city_no": 'dafegn'},
    {"name": '郁南', "id": '14', "pinyin": 'YUMAN', "city_no": 'YUMAN'},
    {"name": '龙游', "id": '165', "pinyin": 'longyou', "city_no": 'longyou'},
    {"name": '河源', "id": '226', "pinyin": 'heyuan', "city_no": 'heyuan'},
    {"name": '涿州', "id": '337', "pinyin": 'ZHUOZHOU', "city_no": 'ZHUOZHOU'},
    {"name": '四会', "id": '77', "pinyin": 'sihui', "city_no": 'sihui'},
    {"name": '蚌埠', "id": '1', "pinyin": 'BENGBU', "city_no": 'BENGBU'},
    {"name": '泰兴', "id": '57', "pinyin": 'TAIXING', "city_no": 'TAIXING'},
    {"name": '固镇', "id": '168', "pinyin": 'guzhen', "city_no": 'guzhen'},
    {"name": '泉州', "id": '12', "pinyin": 'QUANZHOU', "city_no": 'QUANZHOU'},
    {"name": '漳州', "id": '335', "pinyin": 'ZHANGZHOU', "city_no": 'ZHANGZHOU'},
    {"name": '连云港', "id": '48', "pinyin": 'LIANGYUNGANG', "city_no": 'LIANGYUNGANG'},
    {"name": '渭南', "id": '340', "pinyin": 'weinan', "city_no": 'weinan'},
    {"name": '定州', "id": '301', "pinyin": 'dingzhou', "city_no": 'dingzhou'},
    {"name": '岳阳', "id": '334', "pinyin": 'yueyang', "city_no": 'yueyang'},
    {"name": '清远', "id": '81', "pinyin": 'qingyuan', "city_no": 'qingyuan'},
    {"name": '广宁', "id": '76', "pinyin": 'guangning', "city_no": 'guangning'},
    {"name": '罗定', "id": '178', "pinyin": 'luoding', "city_no": 'luoding'},
    {"name": '兰溪', "id": '17', "pinyin": 'LANXI', "city_no": 'LANXI'},
    {"name": '嵩县', "id": '273', "pinyin": 'SONGXIAN', "city_no": 'SONGXIAN'},
    {"name": '献县', "id": '279', "pinyin": 'xianxian', "city_no": 'xianxian'},
    {"name": '湘潭', "id": '63', "pinyin": 'XIANGTIAN', "city_no": 'XIANGTIAN'},
    {"name": '大榭', "id": '315', "pinyin": 'daxie', "city_no": 'daxie'},
    {"name": '舟山', "id": '222', "pinyin": 'zhoushan', "city_no": 'zhoushan'},
    {"name": '巩义', "id": '196', "pinyin": 'gongyi', "city_no": 'gongyi'},
    {"name": '邹平', "id": '35', "pinyin": 'ZHOUPING', "city_no": 'ZHOUPING'},
    {"name": '上海', "id": '310', "pinyin": 'shanghai', "city_no": 'shanghai'},
    {"name": '北海', "id": '200', "pinyin": 'beihai', "city_no": 'beihai'},
    {"name": '绥化', "id": '341', "pinyin": 'SUIHUA', "city_no": 'SUIHUA'},
    {"name": '肇庆', "id": '23', "pinyin": 'ZHAOQING', "city_no": 'ZHAOQING'},
    {"name": '衢州', "id": '13', "pinyin": 'QUZHOU', "city_no": 'QUZHOU'},
    {"name": '萍乡', "id": '230', "pinyin": 'pingxiang', "city_no": 'pingxiang'},
    {"name": '宁乡', "id": '116', "pinyin": 'NINGXIANG', "city_no": 'NINGXIANG'},
    {"name": '嘉兴', "id": '219', "pinyin": 'jiaxing', "city_no": 'jiaxing'},
    {"name": '保定域外', "id": '345', "pinyin": 'baodingyuwai', "city_no": 'baodingyuwai'},
    {"name": '滁州', "id": '8', "pinyin": 'CHUZHOU', "city_no": 'CHUZHOU'},
    {"name": '德化', "id": '224', "pinyin": 'dehua', "city_no": 'dehua'},
    {"name": '郑州', "id": '49', "pinyin": 'ZHENGZHOU', "city_no": 'ZZ'},
    {"name": '南京', "id": '233', "pinyin": 'nanjing', "city_no": 'nanjing'},
    {"name": '龙岩', "id": '241', "pinyin": 'longyan', "city_no": 'longyan'},
    {"name": '三明', "id": '309', "pinyin": 'sanming', "city_no": 'sanming'},
    {"name": '新安', "id": '162', "pinyin": 'xinan', "city_no": 'xinan'},
    {"name": '玉田', "id": '229', "pinyin": 'yutian', "city_no": 'yutian'},
    {"name": '坡头', "id": '100', "pinyin": 'potou', "city_no": 'potou'},
    {"name": '栾川', "id": '318', "pinyin": 'luanchuan', "city_no": 'luanchuan'},
    {"name": '盐城', "id": '54', "pinyin": 'YANCHENG', "city_no": 'YANCHENG'},
    {"name": '南宁', "id": '302', "pinyin": 'nanning', "city_no": 'nanning'},
    {"name": '怀化', "id": '174', "pinyin": 'huaihua', "city_no": 'huaihua'},
    {"name": '亳州', "id": '6', "pinyin": 'BOZHOU', "city_no": 'BOZHOU'},
    {"name": '廊坊', "id": '2', "pinyin": 'LANGFANG', "city_no": 'LF'},
    {"name": '浏阳', "id": '118', "pinyin": 'liuyang', "city_no": 'liuyang'},
    {"name": '海盐', "id": '105', "pinyin": 'haiyan', "city_no": 'haiyan'},
    {"name": '伊川', "id": '177', "pinyin": 'yichuan', "city_no": 'yichuan'},
    {"name": '汝阳', "id": '201', "pinyin": 'ruyang', "city_no": 'ruyang'},
    {"name": '台州', "id": '5', "pinyin": 'TAIZHOUA', "city_no": 'TAIZHOUA'},
    {"name": '桂林', "id": '27', "pinyin": 'GUILIN', "city_no": 'GUILIN'},
    {"name": '常山', "id": '304', "pinyin": 'changshan', "city_no": 'changshan'},
    {"name": '怀来', "id": '218', "pinyin": 'huailai', "city_no": 'huailai'},
    {"name": '葫芦岛', "id": '46', "pinyin": 'HULUDAO', "city_no": 'HULUDAO'},
    {"name": '贵港', "id": '28', "pinyin": 'GUIGANG', "city_no": 'GUIGANG'},
    {"name": '炎陵', "id": '322', "pinyin": 'YANLING', "city_no": 'YANLING'},
    {"name": '惠安', "id": '70', "pinyin": 'huian', "city_no": 'huian'},
    {"name": '金华', "id": '16', "pinyin": 'JINHUA', "city_no": 'JINHUA'},
    {"name": '来安', "id": '144', "pinyin": 'laian', "city_no": 'laian'},
    {"name": '胶州', "id": '36', "pinyin": 'JIAOZHOU', "city_no": 'JIAOZHOU'},
    {"name": '界首', "id": '329', "pinyin": 'jieshou', "city_no": 'jieshou'},
    {"name": '阳朔', "id": '269', "pinyin": 'yangshuo', "city_no": 'yangshuo'},
    {"name": '南安', "id": '72', "pinyin": 'NANAN', "city_no": 'NANAN'},
    {"name": '株洲', "id": '60', "pinyin": 'ZHUZHOU', "city_no": 'ZHUZHOU'},
    {"name": '吴川', "id": '199', "pinyin": 'wuchuan', "city_no": 'wuchuan'},
    {"name": '东台', "id": '239', "pinyin": 'DONGTAI', "city_no": 'DONGTAI'},
    {"name": '湛江', "id": '26', "pinyin": 'ZHANJIANG', "city_no": 'ZHANJIANG'},
    {"name": '黄坡', "id": '274', "pinyin": 'huangpo', "city_no": 'huangpo'},
    {"name": '聊城', "id": '21', "pinyin": 'LIAOCHENG', "city_no": 'LIAOCHENG'},
    {"name": '开封', "id": '53', "pinyin": 'KAIFENG', "city_no": 'KAIFENG'},
    {"name": '阜宁', "id": '260', "pinyin": 'FUNING', "city_no": 'FUNING'},
    {"name": '博爱', "id": '342', "pinyin": 'boai', "city_no": 'boai'},
    {"name": '天津', "id": '18', "pinyin": 'TIANJIN', "city_no": 'TIANJIN'},
    {"name": '南大港', "id": '311', "pinyin": 'nandagang', "city_no": 'nandagang'},
    {"name": '包头', "id": '247', "pinyin": 'baotou', "city_no": 'baotou'},
    {"name": '长沙星沙', "id": '115', "pinyin": 'changshaxingsha', "city_no": 'changshaxingsha'},
    {"name": '永春', "id": '86', "pinyin": 'yongchun', "city_no": 'yongchun'},
    {"name": '孟村', "id": '308', "pinyin": 'mengcun', "city_no": 'mengcun'},
    {"name": '凉山', "id": '323', "pinyin": 'liangshan', "city_no": 'liangshan'},
    {"name": '宣城', "id": '282', "pinyin": 'XUANCHENG', "city_no": 'XUANCHENG'},
    {"name": '天津静海', "id": '327', "pinyin": 'tianjinjinghai', "city_no": 'tianjinjinghai'},
    {"name": '永州', "id": '64', "pinyin": 'YONGZHOU', "city_no": 'YONGZHOU'},
    {"name": '临沂', "id": '257', "pinyin": 'linyi', "city_no": 'linyi'},
    {"name": '巢湖', "id": '74', "pinyin": 'CHAOHU', "city_no": 'CHAOHU'},
    {"name": '阳江', "id": '99', "pinyin": 'yangjiang', "city_no": 'yangjiang'},
    {"name": '青岛', "id": '25', "pinyin": 'QINGDAO', "city_no": 'QINGDAO'},
    {"name": '泗水', "id": '338', "pinyin": 'SISHUI', "city_no": 'SISHUI'},
    {"name": '南沙', "id": '231', "pinyin": 'nansha', "city_no": 'nansha'},
    {"name": '番禺', "id": '19', "pinyin": 'PANYU', "city_no": 'PANYU'},
    {"name": '凤阳', "id": '129', "pinyin": 'FENGYANG', "city_no": 'FENGYANG'},
    {"name": '海宁', "id": '11', "pinyin": 'HAINING', "city_no": 'HAINING'},
    {"name": '临城', "id": '290', "pinyin": 'lincheng', "city_no": 'LC'},
    {"name": '洪泽', "id": '119', "pinyin": 'hognze', "city_no": 'hongze1'},
    {"name": '寿光', "id": '296', "pinyin": 'shouguang', "city_no": 'shouguang'},
    {"name": '沈阳', "id": '336', "pinyin": 'SHENYANG', "city_no": 'SHENYANG'},
    {"name": '廉江', "id": '80', "pinyin": 'lianjiang', "city_no": 'lianjiang'},
    {"name": '洛阳', "id": '55', "pinyin": 'LUOYANG', "city_no": 'LUOYANG'},
    {"name": '淮安', "id": '61', "pinyin": 'HUAIAN', "city_no": 'HUAIAN'},
    {"name": '全椒', "id": '145', "pinyin": 'quanjiao', "city_no": 'quanjiao'},
    {"name": '石家庄', "id": '45', "pinyin": 'SHIJIAZHAUNG', "city_no": 'SJZ'},
    {"name": '文山', "id": '203', "pinyin": 'wenshan', "city_no": 'wenshan'},
    {"name": '东营', "id": '266', "pinyin": 'dongying', "city_no": 'dongying'},
    {"name": '盘锦', "id": '259', "pinyin": 'panjin', "city_no": 'panjin'},
    {"name": '辛集', "id": '171', "pinyin": 'xinji', "city_no": '052360'},
    {"name": '永康', "id": '66', "pinyin": 'yongkang', "city_no": 'YONGKANG'},
    {"name": '上饶', "id": '272', "pinyin": 'shangrao', "city_no": 'shangrao'},
    {"name": '昌乐', "id": '228', "pinyin": 'changle', "city_no": 'changle'},
    {"name": '辉县', "id": '209', "pinyin": 'huixian', "city_no": '453600'},
    {"name": '汝州', "id": '97', "pinyin": 'RUZHOU', "city_no": 'RUZHOU'},
    {"name": '常州', "id": '50', "pinyin": 'CHANGZHOU', "city_no": 'CHANGZHOU'},
    {"name": '石河子', "id": '225', "pinyin": 'shihezi', "city_no": 'shihez'},
    {"name": '昆明', "id": '307', "pinyin": 'kūnmíng', "city_no": 'kūnmíng'},
    {"name": '宁波', "id": '15', "pinyin": 'NINGBO', "city_no": 'NINGBO'},
    {"name": '定兴', "id": '232', "pinyin": 'dingxing', "city_no": 'dingxing'},
    {"name": '文安', "id": '198', "pinyin": 'wenan', "city_no": 'wenan'},
    {"name": '宁国', "id": '283', "pinyin": 'NINGGUO', "city_no": 'NINGGUO'},
    {"name": '灵川', "id": '173', "pinyin": 'lingchuan', "city_no": 'lingchuan'},
    {"name": '商丘', "id": '56', "pinyin": 'SHANGQIU', "city_no": 'SHANGQIU'},
    {"name": '南浔', "id": '314', "pinyin": 'nanxun', "city_no": 'nanxun'},
    {"name": '宿迁', "id": '244', "pinyin": 'suqian', "city_no": 'suqian'},
    {"name": '封开', "id": '172', "pinyin": 'fengkai', "city_no": 'fengkai'},
    {"name": '天长', "id": '237', "pinyin": 'tianchang', "city_no": 'tianchang'},
    {"name": '浦江', "id": '292', "pinyin": 'pujiang', "city_no": 'pujiang'},
    {"name": '睢宁', "id": '333', "pinyin": 'suining', "city_no": 'suining'},
    {"name": '雷州', "id": '187', "pinyin": 'leizhou', "city_no": 'leizhou'},
    {"name": '平谷', "id": '9', "pinyin": 'PINGGU', "city_no": 'PINGGU'},
    {"name": '莱阳', "id": '33', "pinyin": 'LAIYANG', "city_no": 'LAIYANG'},
    {"name": '通辽', "id": '41', "pinyin": 'TONGLIAO', "city_no": 'TONGLIAO'},
    {"name": '怀集', "id": '68', "pinyin": 'huaiji', "city_no": 'huaiji'},
    {"name": '含山', "id": '79', "pinyin": 'hanshan', "city_no": 'hanshan'},
    {"name": '南丰', "id": '330', "pinyin": 'nanfeng', "city_no": 'nanfeng'},
    {"name": '东莞', "id": '20', "pinyin": 'DONGWAN', "city_no": 'DONGWAN'},
    {"name": '莱芜', "id": '258', "pinyin": 'laiwu', "city_no": 'laiwu'},
    {"name": '郎溪', "id": '285', "pinyin": 'LANGXI', "city_no": 'LANGXI'},
    {"name": '昭通', "id": '293', "pinyin": 'zhaotong', "city_no": '昭通'},
    {"name": '大庆', "id": '320', "pinyin": 'daqing', "city_no": 'daqing'},
    {"name": '广德', "id": '284', "pinyin": 'GUANGDE', "city_no": 'GUANGDE'},
    {"name": '临颍', "id": '275', "pinyin": 'linying', "city_no": 'linying'},
    {"name": '容城', "id": '136', "pinyin": 'RONGCHENG', "city_no": 'RONGCHENG'},
    {"name": '郏县', "id": '325', "pinyin": 'jiaxian', "city_no": 'jiaxian'},
    {"name": '建湖', "id": '207', "pinyin": 'jianhu', "city_no": 'jianhu'},
    {"name": '晋江', "id": '67', "pinyin": 'jinjiang', "city_no": 'jinjiang'},
    {"name": '响水', "id": '331', "pinyin": 'XIANGSHUI', "city_no": 'XIANGSHUI'},
    {"name": '卫辉', "id": '181', "pinyin": 'weihui', "city_no": '453100'},
    {"name": '淇县', "id": '343', "pinyin": 'qixian', "city_no": 'qixian'},
    {"name": '信宜', "id": '176', "pinyin": 'xinyi', "city_no": 'xinyi'},
    {"name": '峡江', "id": '328', "pinyin": 'xiajiang', "city_no": 'xiajiang'},
    {"name": '启东', "id": '326', "pinyin": 'qidong', "city_no": 'qidong'},
    {"name": '叶县', "id": '316', "pinyin": 'yexian', "city_no": 'yexian'},
    {"name": '日照', "id": '39', "pinyin": 'RIZHAO', "city_no": 'RIZHAO'},
    {"name": '石家庄昆仑', "id": '344', "pinyin": 'kunlin', "city_no": 'kunlin'},
    {"name": '海安', "id": '58', "pinyin": 'HAIAN', "city_no": 'HAIAN'},
    {"name": '保定', "id": '29', "pinyin": 'BAODING', "city_no": 'BD'},
    {"name": '招远', "id": '289', "pinyin": 'ZHAOYUAN', "city_no": 'ZHAOYUAN'},
    {"name": '射阳', "id": '305', "pinyin": 'SHEYANG', "city_no": 'SHEYANG'},
    {"name": '广州', "id": '24', "pinyin": 'GUANGZHOU', "city_no": 'GUANGZHOU'},
    {"name": '池州', "id": '319', "pinyin": 'CHIZHOU', "city_no": 'CHIZHOU'},
    {"name": '唐山', "id": '92', "pinyin": 'tangshan', "city_no": 'tangshan'},
    {"name": '南昌', "id": '263', "pinyin": 'nanchang', "city_no": 'nanchang'},
    {"name": '郴州', "id": '303', "pinyin": 'chenzhou', "city_no": 'chenzhou'},
    {"name": '吉利', "id": '169', "pinyin": 'jili', "city_no": 'jili'},
    {"name": '瑞安', "id": '313', "pinyin": 'ruian', "city_no": 'ruian'},
    {"name": '孟津', "id": '236', "pinyin": 'mengjin', "city_no": 'mengjin'},
    {"name": '宁阳', "id": '295', "pinyin": 'ningyang', "city_no": 'ningyang'},
    {"name": '合肥', "id": '3', "pinyin": 'HEFEI', "city_no": 'HEFEI'},
)

CITY_NAME_TO_ID: dict[str, str] = {city["name"]: city["id"] for city in CITY_OPTIONS}
CITY_ID_TO_NAME: dict[str, str] = {city["id"]: city["name"] for city in CITY_OPTIONS}
CITY_SELECT_OPTIONS: list[dict[str, str]] = [
    {"value": city["name"], "label": city["name"]} for city in CITY_OPTIONS
]


def _norm_text(value: str) -> str:
    return str(value or "").strip().lower()


def find_city(value: str) -> dict[str, str] | None:
    text = _norm_text(value)
    if not text:
        return None

    for city in CITY_OPTIONS:
        if text in {
            _norm_text(city["name"]),
            _norm_text(city["id"]),
            _norm_text(city["pinyin"]),
            _norm_text(city["city_no"]),
        }:
            return city

    matches = [
        city
        for city in CITY_OPTIONS
        if text in _norm_text(city["name"])
        or text in _norm_text(city["pinyin"])
        or text in _norm_text(city["city_no"])
    ]
    if len(matches) == 1:
        return matches[0]
    return None


def city_id_from_name(city_name: str, default_city_id: str = "62") -> str:
    city = find_city(city_name)
    return city["id"] if city else default_city_id


def city_name_from_id(city_id: str, default_city_name: str = "长沙") -> str:
    return CITY_ID_TO_NAME.get(str(city_id), default_city_name)
